### PR TITLE
Spelling.

### PR DESCRIPTION
**Pull request by RlonRyan**
Cleaning up for Dries007. (So he doesn't have to.)

### CODE REVIEW

**Comment by dries007** [comment]
Wow. Also, is this still used? (cause mojang doesn't like handing out capes, we resolved it by using this: http://www.doubledoordev.net/?p=perks)

**Comment by RlonRyan** [comment]
I have no clue.

**Comment by liach** [comment]
@dries007 Why are you no longer a owner?
 Btw is anyone going to update this?

**Comment by dries007** [comment]
@liach I haven't been an active member of FE for a very long time.

**Pull request merged**
